# Generated by Django 4.1 on 2022-09-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=1000)),
                ('opcionCorrecta', models.CharField(max_length=1000)),
                ('opcion2', models.CharField(max_length=1000)),
                ('opcion3', models.CharField(max_length=1000)),
                ('opcion4', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=100)),
            ],
        ),
    ]
