# Generated by Django 4.1 on 2022-10-22 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=100)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField(verbose_name='Enunciado de la pregunta')),
                ('opcionCorrecta', models.CharField(max_length=1000, verbose_name='Opcion correcta de la pregunta')),
                ('opcion2', models.TextField(verbose_name='Opcion falsa de la pregunta')),
                ('opcion3', models.TextField(verbose_name='Opcion falsa de la pregunta')),
                ('opcion4', models.TextField(verbose_name='Opcion falsa de la pregunta')),
                ('Trivia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TGApp.trivia')),
            ],
        ),
    ]
