# Generated by Django 4.1 on 2022-09-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='opcion2',
            field=models.CharField(max_length=1000, verbose_name='Opcion falsa de la pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='opcion3',
            field=models.CharField(max_length=1000, verbose_name='Opcion falsa de la pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='opcion4',
            field=models.CharField(max_length=1000, verbose_name='Opcion falsa de la pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='opcionCorrecta',
            field=models.CharField(max_length=1000, verbose_name='Opcion correcta de la pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='pregunta',
            field=models.CharField(max_length=1000, verbose_name='Enunciado de la pregunta'),
        ),
    ]
