# Generated by Django 4.1 on 2023-01-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntaquiz',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=0, default=3, max_digits=10, verbose_name='Maximo puntaje'),
        ),
    ]
