# Generated by Django 4.1 on 2022-12-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='respuesta',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
