# Generated by Django 4.1 on 2022-11-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0002_pregunta_autor_preguntasrespondidas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='autor',
            new_name='autorPregunta',
        ),
    ]
