# Generated by Django 4.1 on 2022-09-10 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0002_alter_pregunta_opcion2_alter_pregunta_opcion3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='idAdmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TGApp.admin'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='opcion2',
            field=models.TextField(verbose_name='Opcion falsa de la pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='opcion3',
            field=models.TextField(verbose_name='Opcion falsa de la pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='opcion4',
            field=models.TextField(verbose_name='Opcion falsa de la pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='pregunta',
            field=models.TextField(verbose_name='Enunciado de la pregunta'),
        ),
    ]
