# Generated by Django 4.1 on 2023-01-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0002_alter_preguntaquiz_max_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariotrivia',
            name='puntajeTotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Puntaje Total'),
        ),
    ]
