# Generated by Django 4.1 on 2022-11-03 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0003_rename_autor_pregunta_autorpregunta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='autorPregunta',
            new_name='autor',
        ),
    ]
