# Generated by Django 4.1 on 2022-12-10 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0003_alter_pregunta_opcion2_alter_pregunta_opcion3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta',
        ),
    ]
