# Generated by Django 4.1 on 2023-01-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0003_alter_usuariotrivia_puntajetotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='opcion2',
            field=models.CharField(max_length=350, null=True, verbose_name='Opcion falsa de la pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='opcion3',
            field=models.CharField(max_length=350, null=True, verbose_name='Opcion falsa de la pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='opcion4',
            field=models.CharField(max_length=350, null=True, verbose_name='Opcion falsa de la pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='opcionCorrecta',
            field=models.CharField(max_length=350, null=True, verbose_name='Opcion correcta de la pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta',
            field=models.CharField(max_length=350, null=True, verbose_name='respuesta'),
        ),
    ]
