# Generated by Django 4.1 on 2022-09-10 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0003_trivia_idadmin_alter_pregunta_opcion2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='idAdmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Creador', to='TGApp.admin'),
        ),
    ]
