# Generated by Django 4.1 on 2023-02-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0004_alter_pregunta_opcion2_alter_pregunta_opcion3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=None)),
            ],
        ),
    ]
