# Generated by Django 4.1 on 2022-12-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0004_remove_pregunta_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='puntaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Puntaje obtenido'),
        ),
    ]
