# Generated by Django 4.1 on 2023-01-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0005_pregunta_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='respuesta',
            field=models.CharField(max_length=1000, null=True, verbose_name='respuesta'),
        ),
    ]
