# Generated by Django 4.1 on 2022-09-27 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0006_remove_trivia_idadmin_trivia_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='Trivia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TGApp.trivia'),
        ),
    ]
