# Generated by Django 4.1 on 2023-01-03 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TGApp', '0006_pregunta_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaModelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField(null=True, verbose_name='Enunciado de la pregunta')),
                ('opcionCorrecta', models.CharField(max_length=1000, null=True, verbose_name='Opcion correcta de la pregunta')),
                ('opcion2', models.CharField(max_length=1000, null=True, verbose_name='Opcion falsa de la pregunta')),
                ('opcion3', models.CharField(max_length=1000, null=True, verbose_name='Opcion falsa de la pregunta')),
                ('opcion4', models.CharField(max_length=1000, null=True, verbose_name='Opcion falsa de la pregunta')),
                ('respuesta', models.CharField(max_length=1000, null=True, verbose_name='respuesta')),
                ('puntaje', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Puntaje obtenido')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trivia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TGApp.trivia')),
            ],
        ),
    ]
