# Generated by Django 4.1 on 2022-11-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0006_alter_pregunta_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='Trivia',
            new_name='trivia',
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='opcion2',
            field=models.CharField(max_length=1000, verbose_name='Opcion falsa de la pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='opcion3',
            field=models.CharField(max_length=1000, verbose_name='Opcion falsa de la pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='opcion4',
            field=models.CharField(max_length=1000, verbose_name='Opcion falsa de la pregunta'),
        ),
    ]
