# Generated by Django 4.1 on 2023-02-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0006_alter_pregunta_opcion2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='opcion2',
            field=models.CharField(blank=True, max_length=350, verbose_name='Opcion falsa de la pregunta'),
        ),
    ]
