# Generated by Django 4.1 on 2023-02-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0009_alter_test_file_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_file',
            name='archivo',
            field=models.FileField(upload_to=None, verbose_name='archivo_a_subir'),
        ),
    ]
