# Generated by Django 4.1 on 2023-02-14 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0011_alter_test_file_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='archivo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='archivos', verbose_name='archivo_a_subir'),
            preserve_default=False,
        ),
    ]
