# Generated by Django 4.1 on 2023-03-01 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TGApp', '0013_alter_pregunta_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='archivo',
            field=models.FileField(blank=True, upload_to='archivos', verbose_name='Archivo opcional (imagenes, audios y videos solamente)'),
        ),
        migrations.CreateModel(
            name='user_acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceso', models.BooleanField(default=False, verbose_name='Acceso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
