# Generated by Django 4.1 on 2023-03-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0016_user_inicio_acceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta',
        ),
        migrations.AddField(
            model_name='user_inicio',
            name='trivia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='trivia'),
        ),
    ]
