# Generated by Django 4.1 on 2023-03-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0018_alter_user_inicio_trivia'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_inicio',
            name='trivia_acceso',
            field=models.CharField(blank=True, max_length=100, verbose_name='trivia'),
        ),
    ]
