# Generated by Django 4.1 on 2023-03-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0020_alter_user_inicio_trivia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariotrivia',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
