# Generated by Django 4.1 on 2023-03-14 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0021_usuariotrivia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariotrivia',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
