# Generated by Django 4.1 on 2023-04-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0022_alter_usuariotrivia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='pista',
            field=models.CharField(blank=True, max_length=350, verbose_name='Pista de la pregunta'),
        ),
    ]
