# Generated by Django 4.1 on 2023-05-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0024_testchoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testchoices',
            name='year_in_school',
            field=models.CharField(choices=[('fa', 'facil'), ('me', 'medio'), ('di', 'dificil')], default='fa', max_length=2),
        ),
        migrations.CreateModel(
            name='preguntaChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=100, verbose_name='Texto')),
                ('difi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGApp.testchoices')),
            ],
        ),
    ]
