# Generated by Django 4.1 on 2023-05-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGApp', '0025_alter_testchoices_year_in_school_preguntachoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=1000, verbose_name='Codigo')),
                ('salida', models.CharField(max_length=1000, verbose_name='Salida')),
            ],
        ),
    ]
